Repository brstu/MMIPU-2020, pull requests merged in 2020-10, with the labels that each got.

#21 [Task01] created cpp file and readme.md
  trunk/as005302/task_01/doc/equations.png
  trunk/as005302/task_01/doc/main_eq.png
  trunk/as005302/task_01/doc/readme.md
  trunk/as005302/task_01/doc/sub_eq.png
  trunk/as005302/task_01/src/ConsoleApplication1.cpp
  trunk/as005302/task_01/src/ConsoleApplication1.sln
  trunk/as005302/task_01/src/ConsoleApplication1.vcxproj
  trunk/as005302/task_01/src/ConsoleApplication1.vcxproj.filters
  trunk/as005302/task_01/src/ConsoleApplication1.vcxproj.user
Labels: good first issue

#39 [Task1]Create README.md and .cpp file
  trunk/as005301/task_01/doc/README.md
  trunk/as005301/task_01/doc/img/bQqLbKnkz44.jpg
  trunk/as005301/task_01/doc/img/sTeeR0musAI.jpg
  trunk/as005301/task_01/src/Source.cpp
  trunk/as005301/task_01/src/lab1_1.sln
  trunk/as005301/task_01/src/lab1_1.vcxproj
  trunk/as005301/task_01/src/lab1_1.vcxproj.filters
  trunk/as005301/task_01/src/lab1_1.vcxproj.user
Labels: duplicate

#38 task_01/Create cpp and README
  trunk/as005312/task_01/doc/README.md
  trunk/as005312/task_01/doc/img/bQqLbKnkz44.jpg
  trunk/as005312/task_01/doc/img/sTeeR0musAI.jpg
  trunk/as005312/task_01/src/Source.cpp
  trunk/as005312/task_01/src/lab1.vcxproj
  trunk/as005312/task_01/src/lab1.vcxproj.filters
  trunk/as005312/task_01/src/lab1.vcxproj.user
Labels: duplicate

#31 [doc] AS-54f sample for completion state
  results/as54f/readme.md
Labels: documentation

#56 [fix] [doc] AS-54f Result list impovements
  results/as54f/readme.md
Labels: documentation

#50 [doc] AS-53 sample for completion state
  results/as53/readme.md
Labels: documentation

#36 [Task_02] Modeling Pid regulator
  trunk/as005404/task_02/doc/README.md
  trunk/as005404/task_02/doc/documentation.md
  trunk/as005404/task_02/doc/img/1.png
  trunk/as005404/task_02/doc/img/weq25yeq1lin.png
  trunk/as005404/task_02/doc/img/weq25yeq1nonlin.png
  trunk/as005404/task_02/doc/img/weq4yeq1lin.png
  trunk/as005404/task_02/doc/img/weq4yeq1nonlin.png
  trunk/as005404/task_02/src/task2.cpp
  trunk/as005404/task_02/src/task2.sln
  trunk/as005404/task_02/src/task2.vcxproj
  trunk/as005404/task_02/src/task2.vcxproj.filters
  trunk/as005404/task_02/src/task2.vcxproj.user
Labels: question
