Repository brstu/MMIPU-2020, pull requests merged in 2020-12, with the labels that each got.

#96 [doc] Add task №2
  tasks/task_04/readme.md
Labels: documentation

#104 [Lab-2] Model of a system with a complex transfer function
  trunk/as005310/task_02/doc/doc.md
  trunk/as005310/task_02/doc/img/Linear.png
  trunk/as005310/task_02/doc/img/Non_Linear.png
  trunk/as005310/task_02/doc/readme.md
  trunk/as005310/task_02/src/CMakeLists.txt
  trunk/as005310/task_02/src/task_02.cpp
Labels: question

#136 [Task_02][Group of Prolisko]
  trunk/as005304/task_02/doc/doc.md
  trunk/as005304/task_02/doc/img/Linear.png
  trunk/as005304/task_02/doc/img/Non_Linear.png
  trunk/as005304/task_02/doc/readme.md
  trunk/as005304/task_02/src/CMakeLists.txt
  trunk/as005304/task_02/src/task_02.cpp
Labels: question

#167 [doc] Documentation update for AS-54f #109
  results/as54f/readme.md
Labels: documentation, enhancement

#117 [doc] AS-53 doc update 2020.12.11
  results/as53/readme.md
Labels: documentation

#148 [Task_02] Modeling PID regulator
  trunk/as005321/task_02/doc/readme.md
  trunk/as005321/task_02/doc/src/linear.png
  trunk/as005321/task_02/doc/src/nonlinear.png
  trunk/as005321/task_02/src/task2.cpp
  trunk/as005321/task_02/src/task2.sln
  trunk/as005321/task_02/src/task2.vcxproj
  trunk/as005321/task_02/src/task2.vcxproj.filters
  trunk/as005321/task_02/src/task2.vcxproj.user
Labels: question

#181 [doc] update as-54f result list + small upgrades
  results/as54f/readme.md
Labels: documentation, enhancement

#182 [fix] Directory fix
  trunk/as005405/task_03/README.md
  trunk/as005405/task_03/img/cVjjYW4EH9U.jpg
  trunk/as005405/task_03/img/pIDMWu5vU24.jpg
  trunk/as005405/task_03/task/lab3.cpp
Labels: help wanted

#186 [doc] 2020.12.30 AS-53 Docs Update
  results/as53/readme.md
Labels: documentation
