Repository brstu/MMIPU-2020, pull requests merged in 2020-11, with the labels that each got.

#26 task01 added source code and documentation
  trunk/as005308/task_01/doc/main_eq.png
  trunk/as005308/task_01/doc/readme.md
  trunk/as005308/task_01/doc/screenshot.PNG
  trunk/as005308/task_01/doc/sub_eq.png
  trunk/as005308/task_01/src/ConsoleApplication44.cpp
  trunk/as005308/task_01/src/ConsoleApplication44.sln
  trunk/as005308/task_01/src/ConsoleApplication44.vcxproj
  trunk/as005308/task_01/src/ConsoleApplication44.vcxproj.filters
  trunk/as005308/task_01/src/ConsoleApplication44.vcxproj.user
Labels: bug

#35 [task01]"modeling-controlled-object"
  trunk/as005305/task_01/doc/images/output.png
  trunk/as005305/task_01/doc/images/sub_eq.png
  trunk/as005305/task_01/doc/readme.md
  trunk/as005305/task_01/src/laba1.sln
  trunk/as005305/task_01/src/laba1/Source.cpp
  trunk/as005305/task_01/src/laba1/laba1.vcxproj
  trunk/as005305/task_01/src/laba1/laba1.vcxproj.filters
  trunk/as005305/task_01/src/laba1/laba1.vcxproj.user
Labels: bug

#34 [Task_01] Simple object modelling
  trunk/as005310/task_01/doc/images/result1.png
  trunk/as005310/task_01/doc/images/result2.png
  trunk/as005310/task_01/doc/images/sub_eq.png
  trunk/as005310/task_01/doc/readme.md
  trunk/as005310/task_01/src/Project64.sln
  trunk/as005310/task_01/src/Project64/Project64.vcxproj
  trunk/as005310/task_01/src/Project64/Project64.vcxproj.filters
  trunk/as005310/task_01/src/Project64/Project64.vcxproj.user
  trunk/as005310/task_01/src/Project64/task 1.cpp
Labels: invalid

#74 [doc] AS-53: update statistics
  results/as53/readme.md
Labels: documentation
